#!/usr/bin/env bash

# Script to launch the Dynamic Optics DM control. This script:
#   - creates a dedicated tmux session
#   - launches the DM control inside the session
#   - moves the process to its dedicated cset and applies a RTprio

# Check if the user is root
if [ "$EUID" -eq 0 ]; then
  echo "Please do not run as root as the tmux session will be invisible otherwise."
  exit 1
fi

source cacaovars.*.bash

SESSION_NAME="DO_DM-${CACAO_LOOPNUMBER}"
COMMANDPATH="/home/artao-user/c++Projects/milk-2-dynamic-optics-dm/build"
COMMAND="./milk-2-dynamic-optics-dm"
CPU_SET_NAME="dmdrv"
REAL_TIME_PRIORITY="49"
INPUT_STREAM="dm01disp"

# Check if the tmux session already exists
tmux has-session -t "$SESSION_NAME" 2>/dev/null

if [ $? != 0 ]; then
  echo "Creating new session ${SESSION_NAME}"
  tmux new-session -d -s "$SESSION_NAME"
else
  echo "Session ${SESSION_NAME} already exists. Skipping creation."
fi

# Check if the real-time process is already running
PID=$(pgrep -f "$COMMAND")

if [ -n "$PID" ]; then
  echo "Real-time process is already running with PID $PID. Skipping launch."
else
  echo "Launching real-time process."
  tmux send-keys -t "$SESSION_NAME" "cd $COMMANDPATH" C-m
  tmux send-keys -t "$SESSION_NAME" "$COMMAND $INPUT_STREAM &" C-m
  tmux send-keys -t "$SESSION_NAME" "fg" C-m
  sleep 2

  # Recheck the PID after launch
  PID=$(pgrep -f "$COMMAND")

  # Apply real-time priority and move to CPU set
  echo "Applying real-time priority to PID $PID"
  sudo chrt -r -p "$REAL_TIME_PRIORITY" "$PID"
  echo "Moving PID $PID to CPU set $CPU_SET_NAME"
  sudo cset proc -m -p "$PID" -t "$CPU_SET_NAME"
fi

# End script
echo "Please attach to the session in order to control the camera using:"
echo "tmux a -t $SESSION_NAME"
