#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Launch evaluation of an SHS stream on a gpu "

# Extended description
MSextdescr="Launches the evaluation of an SHS stream on a gpu.
This requires a reference to be recorded and loaded into memory.
"

# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#
RequiredCommands=(milk)
RequiredFiles=(LOOPNUMBER)
RequiredFiles=(LOOPNAME)
RequiredPipes=()
RequiredDirs=()

# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#
MSarg+=( "streamInName:string:stream input name" )
MSarg+=( "nbframe:int:number of frames to stay alive (TEMP)" )

# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
#

source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit
fi
set -u

if [ -f LOOPNUMBER ]; then
    AOLOOPNUMBER=$( head -1 LOOPNUMBER )
else
	echo "Error: no LOOPNUMBER file. Are we running this from the correct directory ?"
    exit
fi
echo "Loop ${AOLOOPNUMBER}"

if [ -f LOOPNAME ]; then
    AOLOOPNAME=$( head -1 LOOPNAME )
else
	echo "Error: no LOOPNAME file. Are we running this from the correct directory ?"
    exit
fi
echo "Loop ${AOLOOPNAME}"

instream="${inputMSargARRAY[0]}"
nbframe="${inputMSargARRAY[1]}"
echo "Stream in: ${instream}"
echo "Number of frame: ${nbframe}"

milk-all << EOF
mload cacaoAOloopControlIOtools
cmd? cacaoio.shsGpuEval

readshmim ${instream}
readshmim ${instream}_AVG
cacaoio.shsGpuEval ..procinfo 1
cacaoio.shsGpuEval ..triggermode 3
cacaoio.shsGpuEval ..triggersname ${instream}
cacaoio.shsGpuEval ..loopcntMax ${nbframe}
cacaoio.shsGpuEval ${instream} ${instream}_AVG
exitCLI
EOF
