#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Set up fps for reshaping a stream of 1D data into a pupil"

# Extended description
MSextdescr="A script setting up a fps for the reshaping function which fills a given mask/pupil with 1D data taken from the pixel lines of the input stream.\n
The parameters are the names of the input stream."

# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#
RequiredCommands=(milk)
RequiredPipes=()
RequiredDirs=()

# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#
MSarg+=( "streamInName:string:input stream name" )
MSarg+=( "streamMaskName:string:mask stream name." )

# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
#

source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit
fi
set -u

instream="${inputMSargARRAY[0]}"
maskstream="${inputMSargARRAY[1]}"
echo "Input stream: ${instream}"
echo "Mask stream: ${maskstream}"

# Delete FPS if it already exists.
if [ -f ${MILK_SHM_DIR}/pupilReshape-${instream}.fps.shm ]; then
    printf "\nFPS already exists. Deleting FPS to recreate it with new parameters.\n"
    rm ${MILK_SHM_DIR}/pupilReshape-${instream}.fps.shm
fi

MILK_QUIET=1 milk << EOF
mload cacaoAOloopControlIOtools

cacaoio.pupilReshape ..procinfo 1
# Set triggermode to 3 (SEMAPHORE) - is triggered by stream update
cacaoio.pupilReshape ..triggermode 3
# Set triggerstream to input stream
cacaoio.pupilReshape ..triggersname "${instream}"
# run indefinitely
cacaoio.pupilReshape ..loopcntMax -1

# Set input streams

readshmim ${instream}
cacaoio.pupilReshape .input_name ${instream}
readshmim ${maskstream}
cacaoio.pupilReshape .mask_name ${maskstream}

# Initialize FPS
cacaoio.pupilReshape _FPSINIT_ "${instream}"

exitCLI
EOF
