#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Average stream"

# Extended description
MSextdescr="Take avg of a stream, copy it to specified location
Optionally, also copy the result to SHM
"

# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#
RequiredCommands=(milk)
RequiredFiles=(LOOPNUMBER)
RequiredPipes=()
RequiredDirs=()

# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#
MSarg+=( "streamInName:string:stream input name" )
MSarg+=( "nbframe:int:number of frames to be averaged" )
MSarg+=( "fitsDir:string:destination folder for fitsfile" )

source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit
fi
set -u

if [ -f LOOPNUMBER ]; then
    AOLOOPNUMBER=$( head -1 LOOPNUMBER )
else
	echo "Error: no LOOPNUMBER file. Are we running this from the correct directory ?"
    exit
fi
echo "Loop ${AOLOOPNUMBER}"

instream="${inputMSargARRAY[0]}"
nbframe="${inputMSargARRAY[1]}"
ARCHDIR="${inputMSargARRAY[2]}"
echo "Stream in: ${instream}"
echo "Number of frame: ${nbframe}"
echo "Fits destination: ${ARCHDIR}"
shmdst="${instream}_AVG"

echo "SHM destination: ${shmdst}"

milk-all << EOF
readshmim ${instream}
streamave ..procinfo 1
streamave ..triggermode 3
streamave ..triggersname ${instream}
streamave ..loopcntMax ${nbframe}
streamave ${instream} ${shmdst} ${nbframe}
saveFITS ${shmdst} "imavg.fits"
exitCLI
EOF

# Save the file
if [ ! -d "${ARCHDIR}" ]; then
  mkdir ${ARCHDIR}
fi
echo Saving to ${ARCHDIR}/${shmdst}_$(date -u --iso-8601=seconds).fits
mv imavg.fits ${ARCHDIR}/${shmdst}_$(date -u --iso-8601=seconds).fits
