#!/usr/bin/env bash

if [ ! -z "${CACAO_FPSPROC_LOG_SHSONGPU_SHS+x}" ]; then
	echo "CACAO_FPSPROC_LOG_SHSONGPU_SHS set to ${CACAO_FPSPROC_LOG_SHSONGPU_SHS}"

    if [ "${CACAO_FPSPROC_LOG_SHSONGPU_SHS}" = "ON" ]; then
        echolog "ON  CACAO_FPSPROC_LOG_SHSONGPU_SHS"

        # Parameters
		CACAO_LOG_NAME="SHS"
		CACAO_LOG_SRC=$CACAO_SHSSTREAM
        CACAO_LOG_DST="fitsLogSHS"
		CACAO_LOG_CUBESIZE=32

        # Record the previous state of CACAO_FPSPROC_LOG_STREAM
        if [ -z "${CACAO_FPSPROC_LOG_STREAM+x}" ]; then
            RESHAPE_WAS_DEFINED=false
        else
            RESHAPE_WAS_DEFINED=true
            ORIGINAL_RESHAPE_DEFINITION=$CACAO_FPSPROC_LOG_STREAM
        fi

        export CACAO_FPSPROC_LOG_STREAM="ON"
        source cacao-fpslistadd-LOG_STREAM
        
        # Restore prefious state of CACAO_FPSPROC_LOG_STREAM
        if [ "$RESHAPE_WAS_DEFINED" = true ]; then
            export CACAO_FPSPROC_LOG_STREAM=$ORIGINAL_RESHAPE_DEFINITION
        else
            unset CACAO_FPSPROC_LOG_STREAM
        fi

    else
        echolog "OFF CACAO_FPSPROC_LOG_SHSONGPU_SHS"
    fi
else
    echo "CACAO_FPSPROC_LOG_SHSONGPU_SHS unset"
fi
