#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Add Zernike WFS offset"


# Extended description
MSextdescr="Modifies Zernike coefficients in SHM and updates the expanded WFS offset.

The Zernike coefficients are represented as a 1D float stream.
Individual coefficients can be changed using their names.
The expansion is done using the wfs pupil mask.
The output is 1D, but can optionally be reshaped to the pupil mask.
"


source milk-script-std-config
source cacao-check-cacaovars

# prerequisites
#
RequiredCommands=( milk )
RequiredFiles=()
RequiredPipes=()
RequiredDirs=()

# Image stream names
IM_MASK="aol${CACAO_LOOPNUMBER}_shsCam_RefMask"
ZC_STREAM="aol${CACAO_LOOPNUMBER}_zernCoeff_WFS"
ZE_1D="aol${CACAO_LOOPNUMBER}_wfszpo" # Output is written to WFS ZPO
ZE_2D="${ZE_1D}_reshape"

# Zernike coefficient names
TiltX="tiltx"
TiltY="tilty"
Defocus="defoc"
Astigmatism45="astig45"
Astigmatism0="astig0"
ComaY="comay"
ComaX="comax"
Trefoil30="tref30"
Trefoil0="tref0"
Spherical="sph"
Astigmatism2nd0="2ndastig0"
Astigmatism2nd45="2ndastig45"
Quadrafoil0="quad0"
Quadrafoil225="quad225"

# Zernike coefficient indicees
declare -A coeffIndex
coeffIndex["${TiltX}"]=1
coeffIndex["${TiltY}"]=2
coeffIndex["${Defocus}"]=3
coeffIndex["${Astigmatism45}"]=4
coeffIndex["${Astigmatism0}"]=5
coeffIndex["${ComaY}"]=6
coeffIndex["${ComaX}"]=7
coeffIndex["${Trefoil30}"]=8
coeffIndex["${Trefoil0}"]=9
coeffIndex["${Spherical}"]=10
coeffIndex["${Astigmatism2nd0}"]=11
coeffIndex["${Astigmatism2nd45}"]=12
coeffIndex["${Quadrafoil0}"]=13
coeffIndex["${Quadrafoil225}"]=14
# Number of Zernike coefficients = max. index+1
NumZern=15

# SCRIPT ARGUMENTS
MSarg+=( "action:string:action (set/setneg/add/sub/check)" )
MSarg+=( "term:string:term (\
${TiltX}/${TiltY}/${Defocus}/${Astigmatism0}/${Astigmatism45}/\
${ComaY}/${ComaX}/${Trefoil30}/${Trefoil0}/${Spherical}/\
${Astigmatism2nd0}/${Astigmatism2nd45}/${Quadrafoil0}/${Quadrafoil225}\
)" )
MSarg+=( "coefficient:float:coefficient value (Integral(Z^2)=Pi)" )

# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
reshape="0"
MSopt+=( "r:reshape:set_reshape::reshape 1D output to 2D mask" )
function set_reshape() {
	reshape="1"
}

source milk-argparse

ACTION="${inputMSargARRAY[0]}"
ZNAME="${inputMSargARRAY[1]}"
CINDEX=-1
if [ -v coeffIndex["${ZNAME}"] ]; then
    CINDEX=${coeffIndex["${ZNAME}"]}
else
    echo "Unknown coefficiont '${ZNAME}'."
    exit 1
fi
echo "Polynome name = ${ZNAME} (index ${CINDEX})"
COEFF=""
# Negative value cannot be passed easily doe to the argument parsing
if [[ ${ACTION} == "setneg" || ${ACTION} == "sub" ]]; then
	# Negate coefficient value if the action requires it
    COEFF="-${inputMSargARRAY[2]}"
else
    COEFF="${inputMSargARRAY[2]}"
fi
echo "Coefficient value = ${COEFF}"
echo "Reshape 2D: ${reshape}"

ACTIONOK=0
if [ ${ACTION} == "check" ]; then
	ACTIONOK=1
fi

# Checking mask
streamcheckOK="OK"
checkstream ${IM_MASK}
if [ ${streamcheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
	cacaomsglog "ERROR streamcheck - WFS mask does not exist"
	exit 1
fi

# Ensuring zernike coefficient image exists
checkstream ${ZC_STREAM}
if [ ${streamcheckOK} == "FAIL" ]; then	
	cacaomsglog "Zernike coefficient stream not existing. Creating stream."
MILK_QUIET=1 milk << EOF
mload milkimagegen
imgen.mkdisk zc_disk ${NumZern} 1 0 0 0
imcpshm zc_disk ${ZC_STREAM}
exit
EOF
    streamcheckOK="OK"
fi

# Set a coefficient
if [[ ${ACTION} == "set" || ${ACTION} == "setneg" ]]; then
	ACTIONOK=1
MILK_QUIET=1 milk << EOF
readshmim ${ZC_STREAM}
setpix ${ZC_STREAM} ${COEFF} ${CINDEX} 0
exit
EOF
fi

# Add to a coefficient
if [[ ${ACTION} == "add" || ${ACTION} == "sub" ]]; then
	ACTIONOK=1
MILK_QUIET=1 milk << EOF
mload milkimagegen
mload milkimagebasic

imgen.mkdisk offset ${NumZern} 1 0 0 0
setpix offset ${COEFF} ${CINDEX} 0
readshmim ${ZC_STREAM}
imgbasic.addim ${ZC_STREAM} offset added_disk 0 0
imcpshm added_disk ${ZC_STREAM}

exit
EOF
fi

if [ ${ACTIONOK} == 0 ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
	cacaomsglog "ERROR action undefined"
	exit 1
else
	# Everything good, now expand the coefficients
MILK_QUIET=1 milk << EOF
mload cacaoAOloopControlIOtools
readshmim ${IM_MASK}
readshmim ${ZC_STREAM}

cacaoio.zernikeGen .2Doutput ${reshape}

cacaoio.zernikeGen ${ZC_STREAM} ${IM_MASK} ${ZE_1D}

exit
EOF
fi

cacaomsglog "END"
