#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Take SHS camera avg, e.g. for darkframes"


# Extended description
MSextdescr="Reads from aolX_shsCam stream
Averages a number of frames
Saves into stream aolX_shsCam_AVG
Saves dark as conf/aolX_shsCam_AVG.fits"

source milk-script-std-config
source cacao-check-cacaovars


NBframe="1000"
MSopt+=( "n:nbframe:set_NBframe:nbframe[long]:set number of frames" )
function set_NBframe() {
	NBframe="$1"
}

source milk-argparse


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_shsCam

if [ ${streamcheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
	cacaomsglog "ERROR streamcheck"
	exit 1
fi

cacaomsglog "NBframe ${NBframe}"

mkdir -p conf

datestring="$(date -u +'%Y-%m-%dT%H:%M:%S.%NZ')"

cacaomsglog "START acquisition"
MILK_QUIET=1 milk << EOF
readshmim aol${CACAO_LOOPNUMBER}_shsCam
streamave ..procinfo 1
streamave ..triggersname aol${CACAO_LOOPNUMBER}_shsCam
streamave ..triggermode 3
streamave ..loopcntMax ${NBframe}
streamave aol${CACAO_LOOPNUMBER}_shsCam aol${CACAO_LOOPNUMBER}_shsCam_AVG ${NBframe}
saveFITS aol${CACAO_LOOPNUMBER}_shsCam_AVG "conf/aol${CACAO_LOOPNUMBER}_shsCam_AVG.fits"
listim
exitCLI
EOF
cacaomsglog "STOP acquisition"
cacaomsglog "SAVED aol${CACAO_LOOPNUMBER}_shsCam_AVG as conf/aol${CACAO_LOOPNUMBER}_shsCam_AVG.fits"


# LOGGING
# see cacaofuncs-log for conventions
#
source cacaofuncs-log
cacao-calib-logFITSfile aol${CACAO_LOOPNUMBER}_shsCam_AVG

cacaomsglog "END"
