#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_MLAT_SLOWDM"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_MLAT_SLOWDM+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_MLAT_SLOWDM"
fi


# FPS name
fpsname="mlat-slowDM"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaopt.mlatslowdm"

# short description
fpsdescr="Measure Latency (slow DM)"




function fpsentry_addmodules() {
	echo "no module to be added"
}


function fpsentry_addcmds() {
	addfpscmd "setval ${fpsfname}.NBiter 20"
	addfpscmd "setval ${fpsfname}.dmstream aol${CACAO_LOOPNUMBER}_dmRM"
	addfpscmd "setval ${fpsfname}.wfsstream aol${CACAO_LOOPNUMBER}_wfsim"
}



source milk-fpslist-addentry


